### ISSUE TITLE
Script crashes sometimes

### ISSUE THREAD

**Issue by dominikn987505** [davwil/venus_kostal_plenticore#2] opened 2023-01-07 21:45 UTC
First of all thank you very much for the script. 
I have installed it, but the script crashes sometimes. In Venus OS is then shown "Connection: No".
After restarting Venus OS the script works like before.
Crashes happens at day Changes 23:59 -> 00:00hr and after some undefined time.
I used the 5 seconds interval you propose in 'kostal.ini'.

My Workaround is now a crontab which starts the kill_me.sh every hour.

And I had an Issue at verifying that the script is working fine:
Run '/data/venus_kostal_plenticore/kostal.py /data/venus_kostal_plenticore/kostal.ini'
did not work for me. I had to type 'python /data/venus_kostal_plenticore/kostal.py /data/venus_kostal_plenticore/kostal.ini'
Maybe you could add it in the readme?

**Comment by davwil** [comment] 2023-01-24 08:20
Dear Dominik,
are you sure, that your kostal.py is executable? 
Regarding the script crashes, that's interesting. Does it just freeze or do you get some error logs? On my installation it never crashed till now - also running with the 5sec interval. If the process really dies, it should be restarted automatically (as it happens when you run the kill_me.sh script.

**Comment by dominikn987505** [comment] 2023-01-26 14:04
Hi,
I'm a little bit confused and really an noob in Linux. I followed exactly your instructions so I thought it is then executable?
How can I get error logs?
The script crashes and the PV-Inverter disappears in the Overview and even in VRM-Portal. After Restarting Cerbo or using the kill skript it starts automatically again. Thats why I use the crontab and the kill_me.sh now.

Another guy wrote me on Facebook that he had problems with incompleted answers from his Kostal Piko. He changed something in his kostal.py which is shown here.
https://pastebin.com/Y4Jwcy6r?fbclid=IwAR2RrEx4Tzi4QFBNP44S-mWppE1MHjuXsOckxUmvsfDKCg9frLD9fd_C1bQ

**Comment by davwil** [comment] 2023-03-05 13:28
Sorry for the late response - I was quite busy...

you can set the exectuable flag e.g.: chmod +x kostal.py, then you might be able to just call the script without 'python3'.
If you have If you say the script crashes repeatetly on day change it would be nice to have some logs - otherwise we don't know what's going on. As I do not have experiences any crashes in 3 installations that I did myself I currently do not think that this is a general problem - but I would be happy if you prove me wrong and I could fix it ;) 

You could start the script manually just before day change (and assumed crash) or start it and collect the logs - I would be happy to look at the error logs :) 

By quickly looking at the pastebin file it looks like the guy's Piko has another api and thus needed some changes there. Which inverter are you using and which api does it have?

**Comment by dominikn987505** [comment] 2023-03-10 22:42
Hi davwil,
I'm using a Kostal Plenticore 
"api_version":"0.2.0",
"hostname":"Kostalwechselrichter",
"name":"PUCK RESTful API",
"sw_version":"01.26.09454"

How can I collect the error logs?

**Comment by davwil** [comment] 2023-04-04 15:37
There are plenty ways - as said you could just manually start the script and observe the logs.
Closing for now, as it's not reproducable. Feel free to re-open if you have a *specific* error log or comparable

**Closed by davwil** 2023-04-04 15:37 UTC
